### ISSUE TITLE
Sprint 2 : Encapsulation Ticket

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/gather-bot#11]
**Release Targets** :

**Current sprint total points**:  20 

**Achieved points**: 12

**Available Team Members**: 
- Ayush 
- Johnson 

**Holidays**: 

**Planned leaves** : 

**Additional working days:** 

**Status for the sprint as of end date:**  22/09/2022

**In progress** 
[Postgres spike](https://github.com/code-mancers/g-bot/issues/16)

**Done :** 
- [Set a scheduler](https://github.com/code-mancers/g-bot/issues/12)
- [Initiate standup](https://github.com/code-mancers/g-bot/issues/3)
- [Add page with only fields](https://github.com/code-mancers/g-bot/issues/13)
- [Dockerise gbot repository](https://github.com/code-mancers/g-bot/issues/32)
- [Create docker-compose for gbot repository](https://github.com/code-mancers/g-bot/issues/36)

**PR review :** 
- [Creating an API end point for the channel](https://github.com/code-mancers/g-bot/issues/14)
- [Creating an API endpoint for fetching the channel members](https://github.com/code-mancers/g-bot/issues/21)

**Moved to next sprint :** 
- [API integration for fetching the channels](https://github.com/code-mancers/g-bot/issues/22)
- [API integration for fetching the channel members](https://github.com/code-mancers/g-bot/issues/23)
- [Postgres spike](https://github.com/code-mancers/g-bot/issues/16)
- [Storing standup data](https://github.com/code-mancers/g-bot/issues/17)
- [Create an end point to fetch the standups from the database](https://github.com/code-mancers/g-bot/issues/18)
- [Integrate the API with the frontend](https://github.com/code-mancers/g-bot/issues/19)

**Comment by SujayPrabhu96** [comment]
1. What went well?
- Basic standup bot working

2. What  didn't go as planned?
- Couldn't complete expected no. of tickets

3. What did you learn?
- Express + TS
- Prisma ORM

4. What can be improved?
- Speed up PR reviews
- Questioning in channel if there is any blocker

**Comment by nishanthmathiyazhagan9704** [comment]
What went well ?
- From my end i was able to write sprint tickets which was better than the last sprint 
- Was able to follow up with the task regularly 
- Ayush & johnson was able to knock of some tickets 

What didn't go as per plan ?
- We couldn't able to knock of the tickets as we have planned , there were some pending tickets which are moved to the next sprint 
- Delays on writing tests for API as ayush was exploring it 

What did i learn ?

- Learnt on how to write sprint tickets in a  better way comparing to the last sprint 
- Learnt to follow up with the folks for the tasks 

What can be improved 
- From my end will try to improve on explaining the tickets in a better way 
- Will be exploring more on project management and try to give up the best way for the g-bot 
- Can also add the writing unit test in the trainings sessions

**Comment by ayushdevelop** [comment]
1. What went well?
    
    - Was able to finish the UI task on time as expected
    -  Was able to build apis for fetching channels and channel members
    -  Was able to resolve bugs by myself

2. What did not go as planned?
    
    -  Failed to take testing setup in account
    -  Failed to write correct tests which elongated the task duration and resulted in pending tickets
    -  Went through too many tutorials
    -  Did not proactively seek help in channels when the blockage was taking a lot of time

3.  What did you learn?
 
     - Time box blockages and beyond that limit reach out for help
     - Do not go through a lot of tutorials trying to know everything at once

4. What can be improved?

    - Adopting the habit of reading documentations instead of watching tutorials, save times and cut lot of unnecessary 
      details
   - Knowing when to ask for help instead of trying to solve it on your own when it is exceeding the time limit.

**Comment by Johnson-Dsouza** [comment]
What went well?
- Both tasks were based on Docker, which I have worked on a lot. 
What  didn't go as planned?
- Docker-compose task which did not have details about postgres and redis.
What did you learn?
- Learned about nodes. 
- Which was a new platform to work with.
What can be improved?
- Go through the node.
