### ISSUE TITLE
Bug: Dev env server failure

### ISSUE THREAD

**Issue by SyedSibtainRazvi** [code-mancers/gather-bot#150]
Bug description:
Dev environment server was crashing due to invalid auth

**Comment by SyedSibtainRazvi** [comment]
Issue:
The dev environment was giving an error invalid Auth on the server side which was making the app crash.

Time & Date of occurrence:
Reported on: 10th Nov at 5:10 PM
Resolved on: 11th Nov at 11:00 AM

Escalation:
Johnson escalated the issue of the Dev environment and informed the team. 

Resolution:
The ENV for slack-bot-token was throwing the error, changed the env for the same and the backend started working.
In the slack g-bot dev app, events were set by the admin and the app started working

Impact:
The Dev Environment had to be stopped.

Preventive measures:
Checking the environmental variables and performing an auth test on this link https://api.slack.com/methods/auth.test/test
before adding the env

**Comment by nishanthmathiyazhagan9704** [comment]
Fixed the issue . Closing this ticket
