### ISSUE TITLE
Test G-bot

### ISSUE THREAD

**Issue by nishanthmathiyazhagan9704** [code-mancers/gather-bot#77]
Task Description : 

- Test GBot Backend main branch deployed at [gbot.codemancers.com](http://gbot.codemancers.com/) using [coolify.codemancers.com](http://coolify.codemancers.com/) -

**Comment by Johnson-Dsouza** [comment]
We have deployed backend server with [gbot.c9s.dev](http://gbot.c9s.dev/) domain.
